version: "3.8"

services:

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: systeme_reparti
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: systeme_reparti
      DB_USER: devuser
      DB_PASSWORD: devpass
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
